title: Github Test Blog
author: ghll1
email: ghll1@tuta.io
description: > # this means to ignore newlines until "baseurl:"
  keyword google search tearms description hah

# social links
twitter_username: ghll1
github_username:  ghll1

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
